name: Build and Test

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore packages
      run: msbuild aspnet-get-started/aspnet-get-started.csproj /t:Restore
     
    - name: Restore NuGet packages
      run: nuget restore aspnet-get-started.sln

    - name: Build project
      run: msbuild aspnet-get-started/aspnet-get-started.csproj /t:Build /p:Configuration=Release
      
    - name: SonarQube Scan
      uses: 'uses: https://github.com/SonarSource/sonar-scanner-cli-action@v1'
      with:
        sonar-project-key: starterdotnetgithubactions
        sonar-project-name: starterdotnetgithubactions
        sonar-project-version: '1.0'
        sonar-sources: '.'
        sonar-host-url: 'http://20.205.44.55:9000/'
        sonar-login: ${{ secrets.SONAR_TOKEN }}

 
